doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        # only needed for MySQL
        # charset: utf8mb4
        # default_table_options:
        #     collate: utf8mb4_unicode_ci

        # TODO: migrate to utf8mb4
        charset:  UTF8
        options: {1002: "SET time_zone = '+00:00'"}
        mapping_types:
            enum:   string

        types:
            casted_decimal_1: Runalyze\Bundle\CoreBundle\Doctrine\Types\CastedDecimalScale1Type
            casted_decimal_2: Runalyze\Bundle\CoreBundle\Doctrine\Types\CastedDecimalScale2Type
            tinyint: Runalyze\Bundle\CoreBundle\Doctrine\Types\TinyIntType
            pipe_array: Runalyze\Bundle\CoreBundle\Doctrine\Types\PipeDelimitedArray
            geohash_array: Runalyze\Bundle\CoreBundle\Doctrine\Types\GeohashArray
            runalyze_pause_array: Runalyze\Bundle\CoreBundle\Doctrine\Types\RunalyzePauseArray
            runalyze_round_array: Runalyze\Bundle\CoreBundle\Doctrine\Types\RunalyzeRoundArray

        # backtrace queries in profiler (increases memory usage per request)
        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            CoreBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CoreBundle/Entity'
                prefix: 'Runalyze\Bundle\CoreBundle\Entity'
                alias: CoreBundle
        hydrators:
            COLUMN_HYDRATOR: Runalyze\Bundle\CoreBundle\Doctrine\Hydrator\ColumnHydrator
        dql:
            datetime_functions:
                from_unixtime: DoctrineExtensions\Query\Mysql\FromUnixtime
                month: DoctrineExtensions\Query\Mysql\Month
                week: DoctrineExtensions\Query\Mysql\Week
                year: DoctrineExtensions\Query\Mysql\Year
            numeric_functions:
                round: DoctrineExtensions\Query\Mysql\Round
