# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%app.secret%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: 'session.handler.native_file'
        save_path: '%app.data_directory%/sessions'
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    cache:
        pools:
            app.cache.activity_uploads:
                adapter: cache.app
                public: true
                default_lifetime: 86400
