jms_translation:
    configs:
        app:
            dirs:
                - '%kernel.project_dir%/src'
                - '%kernel.project_dir%/templates'
            output_dir: '%kernel.project_dir%/translations'
            output-format: 'xlf'