jms_translation:
    configs:
        app:
            dirs: ['%kernel.root_dir%/', '%kernel.root_dir%/../src']
            output_dir: '%kernel.root_dir%/../vendor/runalyze/translations/xlf'
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, log, test, doctrine]
            output-format: 'xlf'