framework:
    default_locale: '%app.locale%'
    translator:
        # default_path: '%kernel.project_dir%/translations'
        fallbacks: ['%app.locale%']
        paths:
            - '%kernel.project_dir%/vendor/runalyze/translations/xlf'
            - '%kernel.project_dir%/vendor/runalyze/translations/gettext'
