twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        RUNALYZE_VERSION: '%app.version%'
        garmin_api_key: '%app.garmin_api_key%'
        openweathermap_api_key: '%app.openweathermap_api_key%'
        darksky_api_key: '%app.darksky_api_key%'
        nokia_here_appid: '%app.nokia_here_appid%'
        nokia_here_token: '%app.nokia_here_token%'
        thunderforest_api_key: '%app.thunderforest_api_key%'
        mapbox_api_key: '%app.mapbox_api_key%'
        locales: '%app.locales%'
    paths:
        '%app.data_directory%/views': __main__
    form_themes:
        - 'form/fields.html.twig'
