<?php

namespace Runalyze\Model\Tag;

/**
 * Generated by hand
 */
class EntityTest extends \PHPUnit\Framework\TestCase {

	public function testSimpleObject() {
		$Tag = new Entity(array(
			Entity::TAG => 'Tag Test'
		));

		$this->assertEquals('Tag Test', $Tag->tag());
	}

}
