imports:
  - { resource: expert_config.yml }
  - { resource: config.yml }

framework:
  assets: ~

monolog:
    channels: ['queue', 'console', 'external_services', 'activity_uploads']
    handlers:
        applog:
            type: stream
            path: '%kernel.root_dir%/../var/logs/symfony.log'
            level: error
        main:
            type: fingers_crossed
            action_level: warning
            handler: file
        file:
            type: stream
            level: debug
        syslog:
            type: syslog
            level: error
        queue:
            type: stream
            level: debug
            path: '%kernel.root_dir%/../var/logs/queue.log'
            channels: ['queue']
        console:
            type: stream
            level: error
            path: '%kernel.root_dir%/../var/logs/console.log'
            channels: ['console']
        external_services:
            type: stream
            level: warning
            path: '%kernel.root_dir%/../var/logs/external_services.log'
            channels: ['external_services']
        activity_uploads:
            type: stream
            level: debug
            path: '%kernel.root_dir%/../var/logs/activity_uploads.log'
            channels: ['activity_uploads']
