imports:
  - { resource: expert_config.yml }
  - { resource: config.yml }

framework:
  validation:
     enable_annotations: true
#     translation_domain: messages
  session:
    handler_id: '%session.handler_id%'
    save_path: '%data_directory%/sessions'
  form: ~
  csrf_protection: true
  assets: ~
  templating:
    engines: ['twig']

twig:
  globals:
    RUNALYZE_VERSION: '%RUNALYZE_VERSION%'
    garmin_api_key: '%garmin_api_key%'
    openweathermap_api_key: '%openweathermap_api_key%'
    darksky_api_key: '%darksky_api_key%'
    nokia_here_appid: '%nokia_here_appid%'
    nokia_here_token: '%nokia_here_token%'
    thunderforest_api_key: '%thunderforest_api_key%'
    mapbox_api_key: '%mapbox_api_key%'
    locales: '%locales%'
  paths:
    '%data_directory%/views': __main__
  form_themes:
     - 'form/fields.html.twig'

monolog:
    channels: ['queue', 'console', 'external_services', 'activity_uploads']
    handlers:
        applog:
            type: stream
            path: '%kernel.root_dir%/../var/logs/symfony.log'
            level: error
        main:
            type: fingers_crossed
            action_level: warning
            handler: file
        file:
            type: stream
            level: debug
        syslog:
            type: syslog
            level: error
        queue:
            type: stream
            level: debug
            path: '%kernel.root_dir%/../var/logs/queue.log'
            channels: ['queue']
        console:
            type: stream
            level: error
            path: '%kernel.root_dir%/../var/logs/console.log'
            channels: ['console']
        external_services:
            type: stream
            level: warning
            path: '%kernel.root_dir%/../var/logs/external_services.log'
            channels: ['external_services']
        activity_uploads:
            type: stream
            level: debug
            path: '%kernel.root_dir%/../var/logs/activity_uploads.log'
            channels: ['activity_uploads']
