imports:
    - { resource: config.yml }

parameters:
  database_host: 127.0.0.1
  database_prefix: runalyze_test_
  database_port: 3306
  database_name: runalyze_test
  database_user: runalyze_test
  database_password:

liip_test_fixtures:
  cache_db:
    sqlite: liip_functional_test.services_database_backup.sqlite
liip_functional_test:
  authentication:
    username: "default"
    password: "defaultPassword"

framework:
  test: ~
  session:
    storage_id: session.storage.mock_file
    name: MOCKSESSID

security:
  firewalls:
    default:
      http_basic: ~

doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver: pdo_sqlite
        path: %kernel.cache_dir%/test.db

services:
  _defaults:
    tags: ['doctrine.fixture.orm']
  Runalyze\Bundle\CoreBundle\Tests\DataFixtures\ORM\:
    resource: '../../tests/CoreBundle/DataFixtures/ORM/*'