monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type:  rotating_file
            max_files: 10
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        syslog:
            type: syslog
            level: error
        prod_queue:
            type: stream
            level: debug
            path: '%kernel.logs_dir%/%kernel.environment%_queue.log'
            channels: ['queue']
        prod_console:
            type: stream
            level: error
            path: '%kernel.logs_dir%/%kernel.environment%_console.log'
            channels: ['console']
        prod_external_services:
            type: stream
            level: warning
            path: '%kernel.logs_dir%/%kernel.environment%_external_services.log'
            channels: ['external_services']
        prod_activity_uploads:
            type: stream
            level: debug
            path: '%kernel.logs_dir%/%kernel.environment%_activity_uploads.log'
            channels: ['activity_uploads']
