parameters:
    app.locales:
        'de': { 'name': 'Deutsch', locale: 'de_DE.UTF-8'}
        'en': { 'name': 'English', locale: 'en_US.UTF-8'}
        'pl': { 'name': 'Polski',  locale: 'pl_PL.UTF-8'}
        'ca': { 'name': 'Català',  locale: 'ca_ES.UTF-8'}
        'nl': { 'name': 'Nederlandse', locale: 'nl_NL.UTF-8'}
        'it': { 'name': 'Italiano', locale: 'it_IT.UTF-8'}
        'es': { 'name': 'Español', locale: 'es_ES.UTF-8'}
        'fr': { 'name': 'Français', locale: 'fr_FR.UTF-8'}
