<?php

namespace Runalyze\Calculation\Elevation\Strategy;

/**
 * Generated by hand
 */
class ReumannWitkamTest extends \PHPUnit\Framework\TestCase {

	public function testSimpleArray() {
        $this->expectException(\RuntimeException::class);
		// This algorithm ist not implemented
		$DP = new ReumannWitkam(array(0, 2, 4, 6, 5, 7, 4, 8, 10, 0), 0);
		$DP->runSmoothing();
	}

}
