<?php

namespace Runalyze\Model\Equipment;

use PHPUnit\Framework\TestCase;

/**
 * Generated by hand
 */
class EntityTest extends TestCase {

	public function testSimpleObject() {
		$Equipment = new Entity(array(
			Entity::NAME => 'Equipment name',
			Entity::NOTES => 'Here are some notes',
			Entity::DISTANCE => 123.45,
			Entity::ADDITIONAL_KM => 50,
			Entity::DATE_START => '2015-01-01',
			Entity::DATE_END => null
		));

		$this->assertEquals('Equipment name', $Equipment->name());
		$this->assertEquals('Here are some notes', $Equipment->notes());
		$this->assertTrue($Equipment->hasStartDate());
		$this->assertEquals('2015-01-01', $Equipment->startDate());
		$this->assertTrue($Equipment->isInUse());
		$this->assertEquals(null, $Equipment->endDate());

		$this->assertEqualsWithDelta(123.45, $Equipment->distance(), 1e-6);
		$this->assertEquals(50, $Equipment->additionalDistance());
		$this->assertEqualsWithDelta(173.45, $Equipment->totalDistance(), 1e-6);
	}

}
